name: Draw ZMK keymaps
on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [main]
    paths: ["config/*"]

jobs:
  draw-keymap:
    if: "!contains(github.event.head_commit.message, '[skip-draw]')"
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      output_folder: "./"
      commit_message: "[skip-build] Update keymap diagram"
