name: Create Release

on:
  workflow_dispatch:
  push:
    tags: ["*"]

jobs:
  build-firmware:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  create-release:
    needs: build-firmware
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION="${GITHUB_REF_NAME}"
          if ! grep -q "^## \['"$VERSION"'\]/" CHANGELOG.md; then
            echo "No changelog found for version $VERSION"
            exit 1
          fi

          echo "# 🎉 Version $VERSION" > release_notes.md
          echo "" >> release_notes.md
          awk '/^## \['"$VERSION"'\]/ { found=1; next; } found && /^## \[/ { exit; } found { print; }' CHANGELOG.md >> release_notes.md
          echo "" >> release_notes.md
          echo "## 📦 Firmware Files" >> release_notes.md
          echo "" >> release_notes.md
          echo "- \`corne_left-nice_nano_v2-zmk.uf2\` - Left half firmware" >> release_notes.md
          echo "- \`corne_right-nice_nano_v2-zmk.uf2\` - Right half firmware" >> release_notes.md
          echo "" >> release_notes.md
          echo "notes_file=release_notes.md" >> $GITHUB_OUTPUT

      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware # Assumes ZMK workflow uploads 'firmware'
          path: firmware

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${GITHUB_REF_NAME}
          name: ${GITHUB_REF_NAME}
          body_path: ${{ steps.changelog.outputs.notes_file }}
          files: |
            firmware/corne_left-nice_nano_v2-zmk.uf2
            firmware/corne_right-nice_nano_v2-zmk.uf2
          draft: false
          prerelease: false
          generate_release_notes: false
